sections:
  - name: Calgary
    description: Calgary Section
    location: Room 101
    contactInfo: 555-121-23456

eventTemplates:
  - name: standard-hike
    description: Standard hike event template
    content: Bring layers and water.
    language: en

notificationTemplates:
  - name: event-created
    titleTemplate: "Event Created: {{title}}"
    bodyTemplate: "{{body}}"
    htmlTemplate: "<p>{{body}}</p>"

  - name: event-cancelled
    titleTemplate: "Event Cancelled: {{title}}"
    bodyTemplate: "{{body}}"
    htmlTemplate: "<p>{{body}}</p>"

  - name: add-to-waitlist
    titleTemplate: "You have been added to the waitlist for {{title}}"
    bodyTemplate: "{{body}}"
    htmlTemplate: "<p>{{body}}</p>"

  - name: registration-cancelled
    titleTemplate: "Your registration for {{title}} has been cancelled"
    bodyTemplate: "{{body}}"
    htmlTemplate: "<p>{{body}}</p>"

  - name: registration-approved
    titleTemplate: "Your registration for {{title}} has been approved"
    bodyTemplate: "{{body}}"
    htmlTemplate: "<p>{{body}}</p>"

  - name: event-registered
    titleTemplate: "You registered for {{title}}"
    bodyTemplate: "You registered for {{title}}"
    htmlTemplate: "You registered for {{title}}"

  - name: event-new-registration
    titleTemplate: "New registration for {{title}}"
    bodyTemplate: "New registration for {{title}}"
    htmlTemplate: "New registration for {{title}}"

  - name: registration-cancelled-manager
    titleTemplate: "Registration Cancelled: {{title}}"
    bodyTemplate: "A registration for {{title}} has been cancelled."
    htmlTemplate: "<p>A registration for {{title}} has been cancelled.</p>"

  - name: registration-approved-manager
    titleTemplate: "Registration Approved: {{title}}"
    bodyTemplate: "A registration for {{title}} has been approved."
    htmlTemplate: "<p>A registration for {{title}} has been approved.</p>"
